import type { Payment } from "./types.finance";

export * from "./types.finance";

export type Role = "ADMIN" | "TEACHER";
export type StudentStatus = "ACTIVE" | "COMPLETED" | "DROPPED";
export type PaymentMethod = "CASH" | "BANK_TRANSFER" | "ONLINE" | "OTHER";
export type PartnerKind = "TEACHER" | "MANAGEMENT";
export type InstallmentStatus = "PAID" | "PARTIAL" | "PENDING" | "OVERDUE";
export type Weekday = "MON" | "TUE" | "WED" | "THU" | "FRI" | "SAT" | "SUN";

export interface AuthUser {
  id: string;
  name: string;
  email: string;
  role: Role;
  teacherId: string | null;
  partnerId: string | null;
}

export interface PartnerRef {
  id: string;
  name: string;
  kind: PartnerKind;
}

export interface ShareDefault {
  partnerId: string;
  percent: number;
  partner: PartnerRef;
}

export interface Subject {
  id: string;
  name: string;
  description: string | null;
  teachers: { id: string; user: { name: string } }[];
  shareDefaults: ShareDefault[];
  _count: { students: number };
}

export interface PartnerTotals {
  studentCount: number;
  activeStudentCount: number;
  totalFinalPrice: number;
  totalCollected: number;
  totalRemaining: number;
  projectedShare: number;
  earnedShare: number;
  pendingShare: number;
  totalPaidOut: number;
  balance: number;
}

export interface Partner extends PartnerRef {
  isActive: boolean;
  userId: string | null;
  teacherId: string | null;
  user: { id: string; name: string; email: string; isActive: boolean; role: Role } | null;
  teacher: { id: string; phone: string | null; subjects: { id: string; name: string }[] } | null;
  totals: PartnerTotals;
}

export interface Teacher {
  id: string;
  phone: string | null;
  user: { id: string; name: string; email: string; isActive: boolean };
  partner: { id: string; name: string; isActive: boolean } | null;
  subjects: { id: string; name: string }[];
  _count: { students: number; classSlots: number };
  totals: PartnerTotals | null;
}

export interface StudentShare {
  partnerId: string;
  partner: PartnerRef;
  percent: number;
  earned?: number;
  projected?: number;
}

export interface Installment {
  id: string;
  studentId: string;
  dueDate: string;
  amount: number;
  paidAmount: number;
  note: string | null;
  status: InstallmentStatus;
  remaining: number;
  student?: {
    id: string;
    admissionNo: number;
    name: string;
    phone: string;
    fatherPhone: string | null;
    teacherId: string;
    status: StudentStatus;
    subject: { name: string };
    teacher: { user: { name: string } };
  };
}

export interface Student {
  id: string;
  /** Sequential admission number generated by the database, starting at 1001. */
  admissionNo: number;
  name: string;
  fatherName: string | null;
  phone: string;
  fatherPhone: string | null;
  email: string | null;
  address: string | null;
  subjectId: string;
  teacherId: string;
  fee: number;
  discount: number;
  finalPrice: number;
  status: StudentStatus;
  enrolledAt: string;
  notes: string | null;
  availableSlots: string[];
  createdAt: string;
  subject: { id: string; name: string };
  teacher: { id: string; user: { name: string } };
  shares: StudentShare[];
  paid: number;
  remaining: number;
  partnerPercent: number;
  companyPercent: number;
  nextDue: { id: string; dueDate: string; remaining: number; status: InstallmentStatus } | null;
  overdueCount: number;
}

export interface StudentClassSlot {
  id: string;
  title: string | null;
  days: Weekday[];
  startTime: string;
  endTime: string;
  location: string | null;
  isActive: boolean;
  teacher: { user: { name: string } };
  subject: { name: string };
}

export interface StudentDetail extends Student {
  payments: Payment[];
  installments: Installment[];
  classSlots: StudentClassSlot[];
}

export interface ClassSlotStudent {
  id: string;
  admissionNo: number;
  name: string;
  fatherName: string | null;
  phone: string;
  fatherPhone: string | null;
  email: string | null;
  status: StudentStatus;
  teacherId: string;
  availableSlots: string[];
}

export interface ClassSlot {
  id: string;
  title: string | null;
  teacherId: string;
  subjectId: string;
  days: Weekday[];
  startTime: string;
  endTime: string;
  location: string | null;
  notes: string | null;
  isActive: boolean;
  teacher: { id: string; phone: string | null; user: { name: string; email: string } };
  subject: { id: string; name: string };
  students: ClassSlotStudent[];
}

export interface TimeSlot {
  start: string;
  end: string;
}
