"use client";

import { admissionNo as formatAdmissionNo } from "@/lib/format";
import { Field, Input } from "@/components/ui/form";
import { Card, CardHeader } from "@/components/ui/display";
import type { StudentFormValues } from "./student-form-values";

interface Props {
  v: StudentFormValues;
  set: <K extends keyof StudentFormValues>(key: K, value: StudentFormValues[K]) => void;
  /** Existing students only. New students receive their number when the record is saved. */
  admissionNo?: number;
}

export function StudentDetailsCard({ v, set, admissionNo }: Props) {
  return (
    <Card>
      <CardHeader title="Student details" description="Personal and contact information." />
      <div className="grid gap-4 p-5 sm:grid-cols-2">
        <Field
          label="Admission number"
          hint={admissionNo ? "Generated by the system and cannot be changed." : "Assigned automatically when you save (1001, 1002, 1003 and so on)."}
        >
          <Input
            value={admissionNo ? formatAdmissionNo(admissionNo) : ""}
            placeholder="Assigned on save"
            readOnly
            disabled
            className="bg-slate-50 font-semibold tabular-nums"
          />
        </Field>
        <Field label="Full name" required>
          <Input value={v.name} onChange={(e) => set("name", e.target.value)} required />
        </Field>
        <Field label="Father name">
          <Input value={v.fatherName} onChange={(e) => set("fatherName", e.target.value)} />
        </Field>
        <Field label="Student phone" required>
          <Input value={v.phone} onChange={(e) => set("phone", e.target.value)} placeholder="03xx-xxxxxxx" required />
        </Field>
        <Field label="Father phone">
          <Input value={v.fatherPhone} onChange={(e) => set("fatherPhone", e.target.value)} placeholder="03xx-xxxxxxx" />
        </Field>
        <Field label="Email">
          <Input type="email" value={v.email} onChange={(e) => set("email", e.target.value)} />
        </Field>
        <Field label="Address" className="sm:col-span-2">
          <Input value={v.address} onChange={(e) => set("address", e.target.value)} />
        </Field>
      </div>
    </Card>
  );
}
